---
# By default egress and ingress are disabled. Define the allowed rules here.
egress:
  - ports:
      - protocol: TCP
        port: 443

ingress:
  - ports:
      - protocol: TCP
        port: 443
