---
virtualmachines:
  - name: "control"
    bootloader: efi
    image: "ansible-navigator-ansible"
    cores: "2"
    memory: "2G"
    image_size: "20Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    services:
      - name: control
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: control-http
    routes:
      - name: control-http
        host: control
        service: control
        targetPort: 80
        tls: true
        tls_termination: Edge
