---
- name: Setup control node
  hosts: controller
  gather_facts: false
  vars:
    USER: rhel
  tasks:
    - name: Become block
      become: true
      block:
        - name: Remove setup bundle
          ansible.builtin.file:
            path: /var/ansible-automation-platform-setup-bundle-2.4-6-x86_64.tar.gz
            state: absent

        - name: Stop register warning
          ansible.builtin.replace:
            path: /etc/yum/pluginconf.d/subscription-manager.conf
            regexp: 'enabled.*$'
            replace: 'enabled = 0'

    - name: Create ansible-navigator.yml
      ansible.builtin.copy:
        content: |
          ---
          ansible-navigator:
            execution-environment:
              container-engine: podman
              image: quay.io/acme_corp/first_playbook_ee:latest
              enabled: false
              pull-policy: never

            playbook-artifact:
              save-as: /home/rhel/ansible-files/{playbook_name}-artifact-{ts_utc}.json

            logging:
              level: debug

        dest: "/home/{{ USER }}/ansible-files/ansible-navigator.yml"
        owner: "{{ USER }}"
        group: "{{ USER }}"
        mode: "0644"
